/* -----------------------------------------------------------------
 * Programmer(s): Cody J. Balos @ LLNL
 * -----------------------------------------------------------------
 * SUNDIALS Copyright Start
 * Copyright (c) 2002-2021, Lawrence Livermore National Security
 * and Southern Methodist University.
 * All rights reserved.
 *
 * See the top-level LICENSE and NOTICE files for details.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 * SUNDIALS Copyright End
 * -----------------------------------------------------------------
 * This is the header file for the KINSOL python interface layer
 * that is not automatically generated by SWIG.
 * -----------------------------------------------------------------*/

#ifndef _KINSOL_PY_H
#define _KINSOL_PY_H

#include <kinsol/kinsol.h>

#ifdef __cplusplus  /* wrapper to enable C++ usage */
extern "C" {
#endif

typedef void* KINPyCallbackFn;
SUNDIALS_EXPORT KINPyCallbackFn KINPyRegisterFn(KINPyCallbackFn f, const char* name);

typedef int (*KINPySysFn)(double* uu, int uu_len, double* fval, int fval_len);
SUNDIALS_STATIC_INLINE KINSysFn KINPyRegisterKINSysFn(KINPySysFn f) {
  return ((KINSysFn) KINPyRegisterFn((KINPyCallbackFn) f, "KINPySysFn"));
}

#ifdef __cplusplus  /* wrapper to enable C++ usage */
}
#endif

#endif