/* -----------------------------------------------------------------
 * Programmer(s): Cody J. Balos @ LLNL
 * -----------------------------------------------------------------
 * SUNDIALS Copyright Start
 * Copyright (c) 2002-2021, Lawrence Livermore National Security
 * and Southern Methodist University.
 * All rights reserved.
 *
 * See the top-level LICENSE and NOTICE files for details.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 * SUNDIALS Copyright End
 * -----------------------------------------------------------------
 * This is the header file for the KINSOL python interface layer
 * that is not automatically generated by SWIG.
 * -----------------------------------------------------------------*/

#ifndef _KINSOL_PY_H
#define _KINSOL_PY_H

#include <kinsol/kinsol.h>

#ifdef __cplusplus  /* wrapper to enable C++ usage */
extern "C" {
#endif

typedef int (*KINPySysFn)(realtype* uu, sunindextype uu_len, realtype* fval, sunindextype fval_len, void* user_data);
SUNDIALS_EXPORT KINSysFn KINPyRegisterKINPySysFn(KINPySysFn f);

// typedef void (*KINErrHandlerFn)(int error_code,
//                                 const char *module, const char *function,
//                                 char *msg, void *user_data);
// SUNDIALS_EXPORT KINErrHandlerFn();

// typedef void (*KINInfoHandlerFn)(const char *module, const char *function,
//                                  char *msg, void *user_data);

#ifdef __cplusplus  /* wrapper to enable C++ usage */
}
#endif

#endif