! This file was automatically generated by SWIG (http://www.swig.org).
! Version 4.0.0
!
! Do not make changes to this file unless you know what you are doing--modify
! the SWIG interface file instead.

! ---------------------------------------------------------------
! Programmer(s): Auto-generated by swig.
! ---------------------------------------------------------------
! SUNDIALS Copyright Start
! Copyright (c) 2002-2023, Lawrence Livermore National Security
! and Southern Methodist University.
! All rights reserved.
!
! See the top-level LICENSE and NOTICE files for details.
!
! SPDX-License-Identifier: BSD-3-Clause
! SUNDIALS Copyright End
! ---------------------------------------------------------------

module fsuncontrol_mrihtol_mod
 use, intrinsic :: ISO_C_BINDING
 use fsundials_control_mod
 use fsundials_types_mod
 use fsundials_context_mod
 implicit none
 private

 ! DECLARATION CONSTRUCTS
 public :: FSUNControlMRIHTol
 public :: FSUNControlMRIHTol_GetSlowController
 public :: FSUNControlMRIHTol_GetFastController
 public :: FSUNControlGetID_MRIHTol
 public :: FSUNControlEstimateStepTol_MRIHTol
 public :: FSUNControlReset_MRIHTol
 public :: FSUNControlSetDefaults_MRIHTol
 public :: FSUNControlWrite_MRIHTol
 public :: FSUNControlSetMethodOrder_MRIHTol
 public :: FSUNControlSetEmbeddingOrder_MRIHTol
 public :: FSUNControlSetErrorBias_MRIHTol
 public :: FSUNControlUpdateMRITol_MRIHTol
 public :: FSUNControlSpace_MRIHTol

! WRAPPER DECLARATIONS
interface
function swigc_FSUNControlMRIHTol(farg1, farg2, farg3) &
bind(C, name="_wrap_FSUNControlMRIHTol") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_PTR), value :: farg2
type(C_PTR), value :: farg3
type(C_PTR) :: fresult
end function

function swigc_FSUNControlMRIHTol_GetSlowController(farg1) &
bind(C, name="_wrap_FSUNControlMRIHTol_GetSlowController") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_PTR) :: fresult
end function

function swigc_FSUNControlMRIHTol_GetFastController(farg1) &
bind(C, name="_wrap_FSUNControlMRIHTol_GetFastController") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_PTR) :: fresult
end function

function swigc_FSUNControlGetID_MRIHTol(farg1) &
bind(C, name="_wrap_FSUNControlGetID_MRIHTol") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_INT) :: fresult
end function

function swigc_FSUNControlEstimateStepTol_MRIHTol(farg1, farg2, farg3, farg4, farg5, farg6, farg7) &
bind(C, name="_wrap_FSUNControlEstimateStepTol_MRIHTol") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
real(C_DOUBLE), intent(in) :: farg2
real(C_DOUBLE), intent(in) :: farg3
real(C_DOUBLE), intent(in) :: farg4
real(C_DOUBLE), intent(in) :: farg5
type(C_PTR), value :: farg6
type(C_PTR), value :: farg7
integer(C_INT) :: fresult
end function

function swigc_FSUNControlReset_MRIHTol(farg1) &
bind(C, name="_wrap_FSUNControlReset_MRIHTol") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_INT) :: fresult
end function

function swigc_FSUNControlSetDefaults_MRIHTol(farg1) &
bind(C, name="_wrap_FSUNControlSetDefaults_MRIHTol") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_INT) :: fresult
end function

function swigc_FSUNControlWrite_MRIHTol(farg1, farg2) &
bind(C, name="_wrap_FSUNControlWrite_MRIHTol") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_PTR), value :: farg2
integer(C_INT) :: fresult
end function

function swigc_FSUNControlSetMethodOrder_MRIHTol(farg1, farg2) &
bind(C, name="_wrap_FSUNControlSetMethodOrder_MRIHTol") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_INT), intent(in) :: farg2
integer(C_INT) :: fresult
end function

function swigc_FSUNControlSetEmbeddingOrder_MRIHTol(farg1, farg2) &
bind(C, name="_wrap_FSUNControlSetEmbeddingOrder_MRIHTol") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_INT), intent(in) :: farg2
integer(C_INT) :: fresult
end function

function swigc_FSUNControlSetErrorBias_MRIHTol(farg1, farg2) &
bind(C, name="_wrap_FSUNControlSetErrorBias_MRIHTol") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
real(C_DOUBLE), intent(in) :: farg2
integer(C_INT) :: fresult
end function

function swigc_FSUNControlUpdateMRITol_MRIHTol(farg1, farg2, farg3, farg4, farg5) &
bind(C, name="_wrap_FSUNControlUpdateMRITol_MRIHTol") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
real(C_DOUBLE), intent(in) :: farg2
real(C_DOUBLE), intent(in) :: farg3
real(C_DOUBLE), intent(in) :: farg4
real(C_DOUBLE), intent(in) :: farg5
integer(C_INT) :: fresult
end function

function swigc_FSUNControlSpace_MRIHTol(farg1, farg2, farg3) &
bind(C, name="_wrap_FSUNControlSpace_MRIHTol") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_PTR), value :: farg2
type(C_PTR), value :: farg3
integer(C_INT) :: fresult
end function

end interface


contains
 ! MODULE SUBPROGRAMS
function FSUNControlMRIHTol(sunctx, hcontrol, tolcontrol) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(SUNControl), pointer :: swig_result
type(C_PTR) :: sunctx
type(SUNControl), target, intent(inout) :: hcontrol
type(SUNControl), target, intent(inout) :: tolcontrol
type(C_PTR) :: fresult 
type(C_PTR) :: farg1 
type(C_PTR) :: farg2 
type(C_PTR) :: farg3 

farg1 = sunctx
farg2 = c_loc(hcontrol)
farg3 = c_loc(tolcontrol)
fresult = swigc_FSUNControlMRIHTol(farg1, farg2, farg3)
call c_f_pointer(fresult, swig_result)
end function

function FSUNControlMRIHTol_GetSlowController(c) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(SUNControl), pointer :: swig_result
type(SUNControl), target, intent(inout) :: c
type(C_PTR) :: fresult 
type(C_PTR) :: farg1 

farg1 = c_loc(c)
fresult = swigc_FSUNControlMRIHTol_GetSlowController(farg1)
call c_f_pointer(fresult, swig_result)
end function

function FSUNControlMRIHTol_GetFastController(c) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(SUNControl), pointer :: swig_result
type(SUNControl), target, intent(inout) :: c
type(C_PTR) :: fresult 
type(C_PTR) :: farg1 

farg1 = c_loc(c)
fresult = swigc_FSUNControlMRIHTol_GetFastController(farg1)
call c_f_pointer(fresult, swig_result)
end function

function FSUNControlGetID_MRIHTol(c) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(SUNControl_ID) :: swig_result
type(SUNControl), target, intent(inout) :: c
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 

farg1 = c_loc(c)
fresult = swigc_FSUNControlGetID_MRIHTol(farg1)
swig_result = fresult
end function

function FSUNControlEstimateStepTol_MRIHTol(c, h, tolfac, dsm, dsm4, hnew, tolfacnew) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(SUNControl), target, intent(inout) :: c
real(C_DOUBLE), intent(in) :: h
real(C_DOUBLE), intent(in) :: tolfac
real(C_DOUBLE), intent(in) :: dsm
real(C_DOUBLE), intent(in) :: dsm4
real(C_DOUBLE), dimension(*), target, intent(inout) :: hnew
real(C_DOUBLE), dimension(*), target, intent(inout) :: tolfacnew
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
real(C_DOUBLE) :: farg2 
real(C_DOUBLE) :: farg3 
real(C_DOUBLE) :: farg4 
real(C_DOUBLE) :: farg5 
type(C_PTR) :: farg6 
type(C_PTR) :: farg7 

farg1 = c_loc(c)
farg2 = h
farg3 = tolfac
farg4 = dsm
farg5 = dsm4
farg6 = c_loc(hnew(1))
farg7 = c_loc(tolfacnew(1))
fresult = swigc_FSUNControlEstimateStepTol_MRIHTol(farg1, farg2, farg3, farg4, farg5, farg6, farg7)
swig_result = fresult
end function

function FSUNControlReset_MRIHTol(c) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(SUNControl), target, intent(inout) :: c
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 

farg1 = c_loc(c)
fresult = swigc_FSUNControlReset_MRIHTol(farg1)
swig_result = fresult
end function

function FSUNControlSetDefaults_MRIHTol(c) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(SUNControl), target, intent(inout) :: c
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 

farg1 = c_loc(c)
fresult = swigc_FSUNControlSetDefaults_MRIHTol(farg1)
swig_result = fresult
end function

function FSUNControlWrite_MRIHTol(c, fptr) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(SUNControl), target, intent(inout) :: c
type(C_PTR) :: fptr
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
type(C_PTR) :: farg2 

farg1 = c_loc(c)
farg2 = fptr
fresult = swigc_FSUNControlWrite_MRIHTol(farg1, farg2)
swig_result = fresult
end function

function FSUNControlSetMethodOrder_MRIHTol(c, q) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(SUNControl), target, intent(inout) :: c
integer(C_INT), intent(in) :: q
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
integer(C_INT) :: farg2 

farg1 = c_loc(c)
farg2 = q
fresult = swigc_FSUNControlSetMethodOrder_MRIHTol(farg1, farg2)
swig_result = fresult
end function

function FSUNControlSetEmbeddingOrder_MRIHTol(c, p) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(SUNControl), target, intent(inout) :: c
integer(C_INT), intent(in) :: p
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
integer(C_INT) :: farg2 

farg1 = c_loc(c)
farg2 = p
fresult = swigc_FSUNControlSetEmbeddingOrder_MRIHTol(farg1, farg2)
swig_result = fresult
end function

function FSUNControlSetErrorBias_MRIHTol(c, bias) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(SUNControl), target, intent(inout) :: c
real(C_DOUBLE), intent(in) :: bias
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
real(C_DOUBLE) :: farg2 

farg1 = c_loc(c)
farg2 = bias
fresult = swigc_FSUNControlSetErrorBias_MRIHTol(farg1, farg2)
swig_result = fresult
end function

function FSUNControlUpdateMRITol_MRIHTol(c, h, tolfac, dsm, dsm4) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(SUNControl), target, intent(inout) :: c
real(C_DOUBLE), intent(in) :: h
real(C_DOUBLE), intent(in) :: tolfac
real(C_DOUBLE), intent(in) :: dsm
real(C_DOUBLE), intent(in) :: dsm4
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
real(C_DOUBLE) :: farg2 
real(C_DOUBLE) :: farg3 
real(C_DOUBLE) :: farg4 
real(C_DOUBLE) :: farg5 

farg1 = c_loc(c)
farg2 = h
farg3 = tolfac
farg4 = dsm
farg5 = dsm4
fresult = swigc_FSUNControlUpdateMRITol_MRIHTol(farg1, farg2, farg3, farg4, farg5)
swig_result = fresult
end function

function FSUNControlSpace_MRIHTol(c, lenrw, leniw) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(SUNControl), target, intent(inout) :: c
integer(C_LONG), dimension(*), target, intent(inout) :: lenrw
integer(C_LONG), dimension(*), target, intent(inout) :: leniw
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
type(C_PTR) :: farg2 
type(C_PTR) :: farg3 

farg1 = c_loc(c)
farg2 = c_loc(lenrw(1))
farg3 = c_loc(leniw(1))
fresult = swigc_FSUNControlSpace_MRIHTol(farg1, farg2, farg3)
swig_result = fresult
end function


end module
