! This file was automatically generated by SWIG (http://www.swig.org).
! Version 4.0.0
!
! Do not make changes to this file unless you know what you are doing--modify
! the SWIG interface file instead.
module fsundials_math_mod
 use, intrinsic :: ISO_C_BINDING
 use fsundials_types_mod
 implicit none
 private

 ! DECLARATION CONSTRUCTS
 public :: FSUNRpowerI
 public :: FSUNRpowerR
 public :: FSUNRCompare
 public :: FSUNRCompareTol

! WRAPPER DECLARATIONS
interface
function swigc_FSUNRpowerI(farg1, farg2) &
bind(C, name="_wrap_FSUNRpowerI") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE), intent(in) :: farg1
integer(C_INT), intent(in) :: farg2
real(C_DOUBLE) :: fresult
end function

function swigc_FSUNRpowerR(farg1, farg2) &
bind(C, name="_wrap_FSUNRpowerR") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE), intent(in) :: farg1
real(C_DOUBLE), intent(in) :: farg2
real(C_DOUBLE) :: fresult
end function

function swigc_FSUNRCompare(farg1, farg2) &
bind(C, name="_wrap_FSUNRCompare") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE), intent(in) :: farg1
real(C_DOUBLE), intent(in) :: farg2
integer(C_INT) :: fresult
end function

function swigc_FSUNRCompareTol(farg1, farg2, farg3) &
bind(C, name="_wrap_FSUNRCompareTol") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE), intent(in) :: farg1
real(C_DOUBLE), intent(in) :: farg2
real(C_DOUBLE), intent(in) :: farg3
integer(C_INT) :: fresult
end function

end interface


contains
 ! MODULE SUBPROGRAMS
function FSUNRpowerI(base, exponent) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE) :: swig_result
real(C_DOUBLE), intent(in) :: base
integer(C_INT), intent(in) :: exponent
real(C_DOUBLE) :: fresult 
real(C_DOUBLE) :: farg1 
integer(C_INT) :: farg2 

farg1 = base
farg2 = exponent
fresult = swigc_FSUNRpowerI(farg1, farg2)
swig_result = fresult
end function

function FSUNRpowerR(base, exponent) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE) :: swig_result
real(C_DOUBLE), intent(in) :: base
real(C_DOUBLE), intent(in) :: exponent
real(C_DOUBLE) :: fresult 
real(C_DOUBLE) :: farg1 
real(C_DOUBLE) :: farg2 

farg1 = base
farg2 = exponent
fresult = swigc_FSUNRpowerR(farg1, farg2)
swig_result = fresult
end function

function FSUNRCompare(a, b) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
real(C_DOUBLE), intent(in) :: a
real(C_DOUBLE), intent(in) :: b
integer(C_INT) :: fresult 
real(C_DOUBLE) :: farg1 
real(C_DOUBLE) :: farg2 

farg1 = a
farg2 = b
fresult = swigc_FSUNRCompare(farg1, farg2)
swig_result = fresult
end function

function FSUNRCompareTol(a, b, tol) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
real(C_DOUBLE), intent(in) :: a
real(C_DOUBLE), intent(in) :: b
real(C_DOUBLE), intent(in) :: tol
integer(C_INT) :: fresult 
real(C_DOUBLE) :: farg1 
real(C_DOUBLE) :: farg2 
real(C_DOUBLE) :: farg3 

farg1 = a
farg2 = b
farg3 = tol
fresult = swigc_FSUNRCompareTol(farg1, farg2, farg3)
swig_result = fresult
end function


end module
